eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8300
spring:
  application:
    name: consumer
app:
  serviceUrl: http://localhost:8100/getUser