eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8600
## 打开feign自带断路器
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: consumer-hystrix-feign
app:
  serviceUrl: http://providor-user/getUser