eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8400
spring:
  application:
    name: consumer-ribbon
app:
  serviceUrl: http://providor-user/getUser